package iscas.bean;
// Generated 2016-3-7 17:33:00 by Hibernate Tools 3.4.0.CR1

/**
 * Emailaddress generated by hbm2java
 */
public class Emailaddress implements java.io.Serializable {

	private Integer id;
	private String fileName;
	private String fileMd5;
	private String emailAddress;
	private String addressType;

	public Emailaddress() {
	}

	public Emailaddress(String fileName, String fileMd5, String emailAddress, String addressType) {
		this.fileName = fileName;
		this.fileMd5 = fileMd5;
		this.emailAddress = emailAddress;
		this.addressType = addressType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileMd5() {
		return this.fileMd5;
	}

	public void setFileMd5(String fileMd5) {
		this.fileMd5 = fileMd5;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

}
