package iscas.bean;
// Generated 2016-3-7 17:33:00 by Hibernate Tools 3.4.0.CR1

/**
 * Labelinfo generated by hbm2java
 */
public class Labelinfo implements java.io.Serializable {

	private Integer id;
	private String fileMd5;
	private String labelString;
	private Integer occurrenceNum;

	public Labelinfo() {
	}

	public Labelinfo(String fileMd5, String labelString, Integer occurrenceNum) {
		this.fileMd5 = fileMd5;
		this.labelString = labelString;
		this.occurrenceNum = occurrenceNum;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileMd5() {
		return this.fileMd5;
	}

	public void setFileMd5(String fileMd5) {
		this.fileMd5 = fileMd5;
	}

	public String getLabelString() {
		return this.labelString;
	}

	public void setLabelString(String labelString) {
		this.labelString = labelString;
	}

	public Integer getOccurrenceNum() {
		return this.occurrenceNum;
	}

	public void setOccurrenceNum(Integer occurrenceNum) {
		this.occurrenceNum = occurrenceNum;
	}

}
