package iscas.bean;
// Generated 2016-3-9 17:29:24 by Hibernate Tools 3.4.0.CR1

/**
 * Labelinfo generated by hbm2java
 */
public class Labelinfo implements java.io.Serializable {

	private Integer id;
	private String fileMd5;
	private String labelString;
	private String refinedLabel;

	public Labelinfo() {
	}

	public Labelinfo(String fileMd5, String labelString, String refinedLabel) {
		this.fileMd5 = fileMd5;
		this.labelString = labelString;
		this.refinedLabel = refinedLabel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileMd5() {
		return this.fileMd5;
	}

	public void setFileMd5(String fileMd5) {
		this.fileMd5 = fileMd5;
	}

	public String getLabelString() {
		return this.labelString;
	}

	public void setLabelString(String labelString) {
		this.labelString = labelString;
	}

	public String getRefinedLabel() {
		return this.refinedLabel;
	}

	public void setRefinedLabel(String refinedLabel) {
		this.refinedLabel = refinedLabel;
	}

}
