package iscas.bean;
// Generated 2016-3-9 17:29:24 by Hibernate Tools 3.4.0.CR1

/**
 * Metrics generated by hbm2java
 */
public class Metrics implements java.io.Serializable {

	private Integer id;
	private String filePair;
	private Float mtricBasedSheetName;

	public Metrics() {
	}

	public Metrics(String filePair, Float mtricBasedSheetName) {
		this.filePair = filePair;
		this.mtricBasedSheetName = mtricBasedSheetName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFilePair() {
		return this.filePair;
	}

	public void setFilePair(String filePair) {
		this.filePair = filePair;
	}

	public Float getMtricBasedSheetName() {
		return this.mtricBasedSheetName;
	}

	public void setMtricBasedSheetName(Float mtricBasedSheetName) {
		this.mtricBasedSheetName = mtricBasedSheetName;
	}

}
