package iscas.bean;
// Generated 2016-3-18 8:34:52 by Hibernate Tools 3.4.0.CR1

/**
 * Sheetdetail generated by hbm2java
 */
public class Sheetdetail implements java.io.Serializable {

	private Integer id;
	private String fileMd5;
	private String sheetName;
	private Integer sheetPosition;
	private Integer sheetNum;
	private Integer rowNum;
	private Integer columnNum;
	private String refinedName;
	private String horizonalLabels;
	private String verticalLabels;
	private String fontLabels;
	private String textLabels;

	public Sheetdetail() {
	}

	public Sheetdetail(String fileMd5, String sheetName, Integer sheetPosition, Integer sheetNum, Integer rowNum,
			Integer columnNum, String refinedName, String horizonalLabels, String verticalLabels, String fontLabels,
			String textLabels) {
		this.fileMd5 = fileMd5;
		this.sheetName = sheetName;
		this.sheetPosition = sheetPosition;
		this.sheetNum = sheetNum;
		this.rowNum = rowNum;
		this.columnNum = columnNum;
		this.refinedName = refinedName;
		this.horizonalLabels = horizonalLabels;
		this.verticalLabels = verticalLabels;
		this.fontLabels = fontLabels;
		this.textLabels = textLabels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileMd5() {
		return this.fileMd5;
	}

	public void setFileMd5(String fileMd5) {
		this.fileMd5 = fileMd5;
	}

	public String getSheetName() {
		return this.sheetName;
	}

	public void setSheetName(String sheetName) {
		this.sheetName = sheetName;
	}

	public Integer getSheetPosition() {
		return this.sheetPosition;
	}

	public void setSheetPosition(Integer sheetPosition) {
		this.sheetPosition = sheetPosition;
	}

	public Integer getSheetNum() {
		return this.sheetNum;
	}

	public void setSheetNum(Integer sheetNum) {
		this.sheetNum = sheetNum;
	}

	public Integer getRowNum() {
		return this.rowNum;
	}

	public void setRowNum(Integer rowNum) {
		this.rowNum = rowNum;
	}

	public Integer getColumnNum() {
		return this.columnNum;
	}

	public void setColumnNum(Integer columnNum) {
		this.columnNum = columnNum;
	}

	public String getRefinedName() {
		return this.refinedName;
	}

	public void setRefinedName(String refinedName) {
		this.refinedName = refinedName;
	}

	public String getHorizonalLabels() {
		return this.horizonalLabels;
	}

	public void setHorizonalLabels(String horizonalLabels) {
		this.horizonalLabels = horizonalLabels;
	}

	public String getVerticalLabels() {
		return this.verticalLabels;
	}

	public void setVerticalLabels(String verticalLabels) {
		this.verticalLabels = verticalLabels;
	}

	public String getFontLabels() {
		return this.fontLabels;
	}

	public void setFontLabels(String fontLabels) {
		this.fontLabels = fontLabels;
	}

	public String getTextLabels() {
		return this.textLabels;
	}

	public void setTextLabels(String textLabels) {
		this.textLabels = textLabels;
	}

}
