package iscas.bean;
// Generated 2016-3-9 10:27:31 by Hibernate Tools 3.4.0.CR1

/**
 * VenronFilelist generated by hbm2java
 */
public class VenronFilelist implements java.io.Serializable {

	private Integer id;
	private Integer fileOrderInGroup;
	private Integer groupId;
	private String fileName;
	private String sendingTime;
	private String sender;
	private String md5;
	private String filePath;

	public VenronFilelist() {
	}

	public VenronFilelist(Integer fileOrderInGroup, Integer groupId, String fileName, String sendingTime, String sender,
			String md5, String filePath) {
		this.fileOrderInGroup = fileOrderInGroup;
		this.groupId = groupId;
		this.fileName = fileName;
		this.sendingTime = sendingTime;
		this.sender = sender;
		this.md5 = md5;
		this.filePath = filePath;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFileOrderInGroup() {
		return this.fileOrderInGroup;
	}

	public void setFileOrderInGroup(Integer fileOrderInGroup) {
		this.fileOrderInGroup = fileOrderInGroup;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getSendingTime() {
		return this.sendingTime;
	}

	public void setSendingTime(String sendingTime) {
		this.sendingTime = sendingTime;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
